### ISSUE TITLE
`qx upgrade` is too simplistic

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qx-cli#18]
The upgrade is very basic at the moment - notable missing support is for libraries and environment settings, both of which should be fairly easy to implement and would be really useful for a lot of projects

**Comment by cboulanger** [comment]
I‘ll be looking into what it would have needed to generate by Bibliograph ˋcompile.jsonˋ from the original ˋconfig.jsonˋ. just need time! I hope I‘ll have some time in October, and could contribute that then.

**Comment by johnspackman** [comment]
This issue was moved to qooxdoo/qooxdoo-compiler#80
