### ISSUE TITLE
Streamline options

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#35]
Options should only be displayed if they are really available in a command. I would therefore argue for not including any default options (not even `--verbose`). Instead, they should be listed, when implemented, in each command class, even if this leads to duplicate code. For example, they should be removed completely here: https://github.com/qooxdoo/qooxdoo-cli/blob/master/commands/contrib.js

**Comment by hkollmann** [comment]
Is it possible to have some sort of inheritance here?

**Comment by cboulanger** [comment]
@hkollmann There already is inheritance, but I'd like to avoid it since it could lead to wrong documentation if an option is inherited but not implemented. Plus I think often there are often different  aspects to the same option name in different commands. So I'd rather duplicate option descriptions.

**Comment by hkollmann** [comment]
It's done with pr #61
