### ISSUE TITLE
Exchange 'path' with 'upath' module to normalize windows paths to unix paths

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#40]
NodeJS on windows can deal with unix paths, so there is no need to work with windows paths at all. We should be able to safely exchange the 'path' module with the 'upath' module (https://www.npmjs.com/package/upath). You can test it in the 'upath' branch: https://github.com/qooxdoo/qooxdoo-cli/tree/upath

**Comment by cboulanger** [comment]
@hkollmann can you test the branch?

**Comment by hkollmann** [comment]
It's working. It's compatible to the add_mobile PR.

**Comment by hkollmann** [comment]
Done with merge #43. Thank you cboulanger
