### ISSUE TITLE
qx contrib publish: allow overriding of version number

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#47]
`qx contrib publish` at the moment increments the existing version number according to the release type (major, minor, patch ...). We should  add a `-V/--version` option that allows to manually set the version number.

**Comment by cboulanger** [comment]
A contrib should have a demo, which allows to see what it does and could be used in unit tests for quality control. qx contrib publish will warn if there isn't one and recommend to add it via `qx contrib init`

**Comment by cboulanger** [comment]
More changes: 
- `qx contrib publish` should also allow to enter a custom release message
- in the confirmation, add the release type (major, minor,...) to the confirmation message

**Comment by johnspackman** [comment]
This issue was moved to qooxdoo/qooxdoo-compiler#82
