### ISSUE TITLE
Create individual tests for each command

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#48]
Currently, the travis test consists of one long `.travis.yml` file executing CLI commands. We need a setup in which each command and subcommand is in its own file. The question is if we should a) use a JS test framework and run the CLI commands from JS, or simply b) sequentially run all the scripts in a subdirectory, each returning exit code 0 in case everything worked, and >0 if not. Third option c) a pure bash/Command line test framework (there must be some, haven't done the research yet).

**Comment by johnspackman** [comment]
This issue was moved to qooxdoo/qooxdoo-compiler#83
