### ISSUE TITLE
Add option to ignore global symbols

### ISSUE THREAD

**Issue by mbgonicus** [qooxdoo/qx-cli#57]
Right now the only way to prevent warnings for undeclared globals is to add an `@ignore` flag in the single qx classes, but there is no way to state symbols that are ignored in general. 

With the old generator one could write something like
```json
      "lint-check" : {
          "allowed-globals" : [
            "d3",
            "mockup",
            "mockup_mode",
            "svg"
          ]
      }
```

I reckon we should put an option to globally ignore symbols.

**Comment by hkollmann** [comment]
See this too: https://github.com/qooxdoo/qooxdoo-cli/issues/54

**Comment by johnspackman** [comment]
This issue was moved to qooxdoo/qooxdoo-compiler#86
