### ISSUE TITLE
new command: "qx contrib init"

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-cli#58]
The command transforms a non-contrb library into a contrib that can be published right away, by executing the following steps:

1. add a `qooxdoo.json` file, containing `{ "libraries":{"path":"."}, "applications":{"path":"demo/default"}}`
2. creating a demo application in `demo/default`, if it doesn't already exist. 
3. consistency checks for `Manifest.json` and `compile.json`

**Comment by johnspackman** [comment]
This issue was moved to qooxdoo/qooxdoo-compiler#87
