### ISSUE TITLE
Compile issues with `cli` and `compiler`

### ISSUE THREAD

**Issue by johnspackman** [qooxdoo/qx-cli#74]
An ongoing difficulty with cli and compiler is that they are very closely linked (almost co-dependent) and yet have independent development paths; this leads to situations where the travis/sausage unit tests for one can fail because one of the projects is not using the correct branch of the other project.  

Making Travis tests depend on published npm versions isn't suitable because `compiler` is required to go through it's own unit test cycle before merging into master and being published to npm; but some of the `compiler` unit tests rely on `cli` to get built, and if there is a change in `compiler` which breaks `cli`, then this forces us to release something to npm that breaks the live `cli` until it has gone through it's own test/publish cycle.  

It seems that we would sometimes (often?) want to tie branches of `cli` and `compiler` together, have them unit tested together, and released together.

How would it be if we merged `cli` and `compiler`??  Both are APIs so there shouldn't be much conflict, and at present the three contributors are the same people so it seems like a natural fit from a time-management point of view; fundamentally it would make releasing so much simpler because the unit tests would be self contained.

**Comment by cboulanger** [comment]
I wouldn't mind. In the end, qooxdoo-cli has no purpose of its own, it is fundamentally dependent on the compiler (even the contrib commands make no sense without it). So yes +1 for merging.

**Comment by hkollmann** [comment]
As long as the compiler api stays public i agree to the merging.
We could handle the naming problem this way:
  - deprecate qxcompiler on npm
  - deprecate qx-cli on npm
  - merge qooxdoo-cli into qooxdoo-compiler
  - rename the package to qooxdoo-compiler instead of qxcompiler.
  - delete qooxdoo-cli 

We should think about removing some of the older qooxdoo repositories. But that is another story.

**Comment by johnspackman** [comment]
👍 i'll get started on that during the holidays hopefully.

**Comment by hkollmann** [comment]
see here too: https://github.com/qooxdoo/qooxdoo/issues/9471

**Comment by hkollmann** [comment]
and here: https://github.com/qooxdoo/qooxdoo/issues/9369

**Comment by hkollmann** [comment]
done with qooxdoo/qooxdoo-compiler#69
